import {
  abosayyah,
  estekana,
  express,
  mahasil,
  medhatpasha,
  parkmycar,
  sahalnoom,
} from "@/images/clients/companies-jpg";
import { midhat1, midhat2, midhat3, midhat4, midhat5, midhat6, midhat7, midhat8, sahalnoom1, sahalnoom2, sahalnoom3, sahalnoom4, sahalnoom5, sahalnoom6, sahalnoom7, sahalnoom8, sahalnoom9 } from '../images/companies-images'; 

export const ourWork = [
  {
    id: 1,
    title: "Abosayyah",
    description: "Description for Abosayyah",
    address: "Address 1",
    type: "Type 1",
    establishmentDate: "2022-01-01",
    area: "Area 1",
    chairs: 20,
    tables: 10,
    numOfEmployees: 5,
    AvgMonthlyVisits: 1000,
    img: abosayyah,
    link: "/work/abosayyah",
  },
  {
    id: 2,
    title: "Estekana",
    description: "Description for Estekana",
    address: "Address 2",
    type: "Type 2",
    establishmentDate: "2022-02-01",
    area: "Area 2",
    chairs: 30,
    tables: 15,
    numOfEmployees: 10,
    AvgMonthlyVisits: 2000,
    img: estekana,
    link: "/work/estekana",
  },
  {
    id: 3,
    title: "Illustrate",
    description: "Description for Illustrate",
    address: "Address 3",
    type: "Type 3",
    establishmentDate: "2022-03-01",
    area: "Area 3",
    chairs: 25,
    tables: 12,
    numOfEmployees: 8,
    AvgMonthlyVisits: 1500,
    img: express,
    link: "/work/illustrate",
  },
  {
    id: 4,
    title: "Mahasil",
    description: "Description for Mahasil",
    address: "Address 4",
    type: "Type 4",
    establishmentDate: "2022-04-01",
    area: "Area 4",
    chairs: 40,
    tables: 20,
    numOfEmployees: 12,
    AvgMonthlyVisits: 2500,
    img: mahasil,
    link: "/work/mahasil",
  },
  {
    id: 5,
    title: "Midhatpasha",
    description: "Description for Midhat",
    address: "Address 5",
    type: "Type 5",
    establishmentDate: "2022-05-01",
    area: "Area 5",
    chairs: 35,
    tables: 18,
    numOfEmployees: 9,
    AvgMonthlyVisits: 1200,
    img: medhatpasha,
    link: '/work/midhatpasha',
    images: [midhat1, midhat2, midhat3, midhat4, midhat5, midhat6, midhat7, midhat8], // Add images array here
  },
  {
    id: 6,
    title: "Park My Car",
    description: "Description for Park My Car",
    address: "Address 6",
    type: "Type 6",
    establishmentDate: "2022-06-01",
    area: "Area 6",
    chairs: 28,
    tables: 14,
    numOfEmployees: 6,
    AvgMonthlyVisits: 800,
    img: parkmycar,
    link: "/parkmycar",
  },
  {
    id: 7,
    title: "Sahalnoom",
    description: "Description for Sahel Nom",
    address: "Address 7",
    type: "Type 7",
    establishmentDate: "2022-07-01",
    area: "Area 7",
    chairs: 50,
    tables: 25,
    numOfEmployees: 15,
    AvgMonthlyVisits: 3000,
    img: sahalnoom,
    link: '/work/sahalnoom',
    images: [sahalnoom1, sahalnoom2, sahalnoom3, sahalnoom4, sahalnoom5, sahalnoom6, sahalnoom7, sahalnoom8, sahalnoom9], // Add images array here
  },
];
