import {
  abosayyah,
  estekana,
  express,
  mahasil,
  medhatpasha,
  parkmycar,
  sahalnoom,
} from "@/images/clients/companies-jpg";
import { midhat1, midhat2, midhat3, midhat4, midhat5, midhat6, midhat7, midhat8,
   sahalnoom1, sahalnoom2, sahalnoom3, sahalnoom4, sahalnoom5, sahalnoom6, sahalnoom7, sahalnoom8, sahalnoom9,
   abusayyah1,
   abusayyah2,
   abusayyah3,
   abusayyah4,
   abusayyah5,
   abusayyah6,
   abusayyah7,
   abusayyah8,
   abusayyah9,
   abusayyah10,
   abusayyah11,
   abusayyah12,
   abusayyah13,
   abusayyah14,
   
   esticana1,
   esticana2,
   esticana3,
   esticana4,
   esticana5,
   esticana6,
 
 
   parkmycar1,
   parkmycar2,
   parkmycar3,
   parkmycar4,
   parkmycar5,
   parkmycar6,
   parkmycar7,
   parkmycar8,
   parkmycar9,
   parkmycar10,
   parkmycar11,
 
   sahalnomexpres1,
   sahalnomexpres2,
   sahalnomexpres3,
   sahalnomexpres4,
   sahalnomexpres5,
   sahalnomexpres6,
   sahalnomexpres8,
   sahalnomexpres9,
   sahalnomexpres10,
   sahalnomexpres11,
   sahalnomexpres12,
   sahalnomexpres13,
  } from '../images/companies-images'; 

export const ourWork = [
  {
    id: 1,
    title: "Abusayyah",
    name: "Abu Sayyah Cafeteria L.L.C",
    description: "Description for Abosayyah",
    address: "Dubai, Arjan, Al Sayyah Residence – Block F",
    type: "Coffee shop and shisha services.",
    establishmentDate: "2022-01-01",
    area: "1,090.71 sq. ft",
    chairs: 19,
    tables: 16,
    numOfEmployees: 5,
    AvgMonthlyVisits: 1483.88,
    img: abosayyah,
    link: "/work/abusayyah",
    images: [abusayyah1,
      abusayyah2,
      abusayyah3,
      abusayyah4,
      abusayyah5,
      abusayyah6,
      abusayyah7,
      abusayyah8,
      abusayyah9,
      abusayyah10,
      abusayyah11,
      abusayyah12,
      abusayyah13,
      abusayyah14]
  },
  {
    id: 2,
    title: "Estekana",
    name:"Estekana Café L.L.C",
    description: "Description for Estekana",
    address: "Dubai, Business Bay, Blue Bay Tower",
    type: "Cafeteria, coffee shop, juices, and sweets.",
    establishmentDate: "21/02/2018",
    area: "406.00 sq. ft",
    chairs: 25,
    tables: 11,
    numOfEmployees: 8,
    AvgMonthlyVisits:  3521.50,
    img: estekana,
    link: "/work/estekana",
    images:[ esticana1,
      esticana2,
      esticana3,
      esticana4,
      esticana5,
      esticana6,
    ]
  },
  {
    id: 3,
    title: "SahElNomExpressCafe",
    name: "Sah El Nom Express Café & Restaurant L.L.C",
    description: "Description for Sah El Nom Express Café ",
    address: "Dubai, Business Bay, Blue Bay Tower",
    type: "Coffee shop, shisha services, and restaurant",
    establishmentDate: "29/11/2015",
    area: "3,813.00 sq. ft",
    chairs: 230,
    tables: 84,
    numOfEmployees: 78,
    AvgMonthlyVisits: 10145.88,
    img: express,
    link: "/work/sahelnomexpresscafe",
    images: [sahalnomexpres1,
      sahalnomexpres2,
      sahalnomexpres3,
      sahalnomexpres4,
      sahalnomexpres5,
      sahalnomexpres6,
      sahalnomexpres8,
      sahalnomexpres9,
      sahalnomexpres10,
      sahalnomexpres11,
      sahalnomexpres12,
      sahalnomexpres13,]
  },
  {
    id: 5,
    title: "Midhatpasha",
    name: "Midhat Pasha Café L.L.C",
    description: "Description for Midhat",
    address: "Dubai, Arjan, Al Sayyah Residence – Block E",
    type: "Coffee shop and shisha services",
    establishmentDate: "2022-05-01",
    area: "8,589.13 sq. ft (indoors & outdoors)",
    chairs: 423,
    tables: 99,
    numOfEmployees: 48,
    AvgMonthlyVisits: 13089.13,
    img: medhatpasha,
    link: '/work/midhatpasha',
    images: [midhat1, midhat2, midhat3, midhat4, midhat5, midhat6, midhat7, midhat8], // Add images array here
  },
  {
    id: 6,
    title: "ParkMyCar",
    name: "Park My Car Valet Parking Services L.L.C",
    description: "Description for Park My Car",
    address: "Address 6",
    type: "Type 6",
    establishmentDate: "2022-06-01",
    area: "Area 6",
    chairs: 28,
    tables: 14,
    numOfEmployees: 6,
    AvgMonthlyVisits: 800,
    img: parkmycar,
    link: "/work/parkmycar",
    images: [parkmycar1,
      parkmycar2,
      parkmycar3,
      parkmycar4,
      parkmycar5,
      parkmycar6,
      parkmycar7,
      parkmycar8,
      parkmycar9,
      parkmycar10,
      parkmycar11,
    ]
  },
  {
    id: 7,
    title: "Sahalnoom",
    name: "Sah El Nom Café & Restaurant",
    description: "Description for Sahel Nom",
    address: "Dubai, Business Bay, Blue Bay Tower",
    type: "Coffee shop, shisha services, and restaurant.",
    establishmentDate: "29/11/2015",
    area: "3,813.00 sq. ft",
    chairs: 230,
    tables: 84,
    numOfEmployees: 78,
    AvgMonthlyVisits: 10145.88,
    img: sahalnoom,
    link: '/work/sahalnoom',
    images: [sahalnoom1, sahalnoom2, sahalnoom3, sahalnoom4, sahalnoom5, sahalnoom6, sahalnoom7, sahalnoom8, sahalnoom9], // Add images array here
  },
];
